ISO3_TO_NAME = {
    "ARG": "Argentina",
    "BHS": "Bahamas",
    "BLZ": "Belice",
    "BOL": "Bolivia",
    "BRA": "Brasil",
    "BRB": "Barbados",
    "CHL": "Chile",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "DOM": "República Dominicana",
    "ECU": "Ecuador",
    "GTM": "Guatemala",
    "GUF": "Guayana Francesa",
    "GUY": "Guyana",
    "HND": "Honduras",
    "HTI": "Haití",
    "JAM": "Jamaica",
    "MEX": "México",
    "NIC": "Nicaragua",
    "PAN": "Panamá",
    "PER": "Perú",
    "PRY": "Paraguay",
    "SLV": "El Salvador",
    "SUR": "Surinam",
    "TTO": "Trinidad y Tobago",
    "URY": "Uruguay",
    "VEN": "Venezuela",
}

ISO3_TO_NAME_ENGLISH = {
    "ARG": "Argentina",
    "BHS": "Bahamas",
    "BLZ": "Belize",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "CHL": "Chile",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "GTM": "Guatemala",
    "GUF": "French Guiana",
    "GUY": "Guyana",
    "HND": "Honduras",
    "HTI": "Haiti",
    "JAM": "Jamaica",
    "MEX": "Mexico",
    "NIC": "Nicaragua",
    "PAN": "Panama",
    "PER": "Peru",
    "PRY": "Paraguay",
    "SLV": "El Salvador",
    "SUR": "Suriname",
    "TTO": "Trinidad and Tobago",
    "URY": "Uruguay",
    "VEN": "Venezuela",
}
