ISO3_TO_NAME = {
    "ARG": "Argentina",
    "BRA": "Brasil",
    "BLZ": "Belice",
    "BOL": "Bolivia",
    "CHL": "Chile",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "DOM": "República Dominicana",
    "ECU": "Ecuador",
    "GTM": "Guatemala",
    "GUF": "Guayana Francesa",
    "GUY": "Guyana",
    "HND": "Honduras",
    "HTI": "Haití",
    "MEX": "México",
    "NIC": "Nicaragua",
    "PAN": "Panamá",
    "PRY": "Paraguay",
    "PER": "Perú",
    "SLV": "El Salvador",
    "SUR": "Surinam",
    "URY": "Uruguay",
    "VEN": "Venezuela",
}
